### ISSUE TITLE
Re-naming/re-org work

### ISSUE THREAD

**Issue by danamlewis** [loudnate/openaps-mmhistorytools#30]
Per dev convo tonight, requesting a look at the names and organization . Consider "clean" and "prepare"? 

@loudnate @bewest @scottleibrand @amazaheri @channemann

**Comment by channemann** [comment]
This setup gist provides some background on the reports and the alias I (as derived from @loudnate) use: https://gist.github.com/channemann/d29abfabffd365ed1735 (don't worry about the bulk of the gist, just the stuff at "Add a whole bunch of reports" and below).

So the four components in `openaps-mmhistorytools` that are currently split out in this sequence are `clean`, `reconcile`, `resolve`, and `normalize`, and they are used in that order. There is also a `trim` usage, but that is not explicitly called.

The purpose of each step is explained briefly in the [readme](https://github.com/loudnate/openaps-mmhistorytools/blob/master/README.md) and more completely in [historytools.py](https://github.com/loudnate/openaps-mmhistorytools/blob/master/openapscontrib/mmhistorytools/historytools.py). In short, `clean` handles issues with duplicated bolus wizard entries and unpaired suspend/resume records, `reconcile` handles issues with temporary basals, `resolve` converts the entries into a consistent record structure, and `normalize` makes all the records relative in time (to a t = 0 point) and basal records relative to the basal schedule (so that they're net, not absolute). `openaps-predict` uses only the output of `normalize`, combined with some files generated elsewhere.

I believe the issue that was raised was potential confusion/error in writing as many `report add` lines into the setup of `openaps.ini` as are shown in the setup doc. This seems to be a small inconvenience compared to the added testing flexibility afforded by keeping the functions split. A compromise would be to created some sort of alias internal to the `mmhistorytools` plugin that would permit calling, for example `clean` and `reconcile` with one usage command and `resolve` and `normalize` with another. I am unaware of what this would take effort-wise. I would recommend against using the alias "clean" for one of the new internal aliases as it would require renaming an existing usage; perhaps another appropriate term can be suggested.

I hope that sets the scene accurately. Thoughts?

**Comment by loudnate** [comment]
Sounds good to me. Yeah, unfortunately we can't re-use "clean" (at the moment) because it will break existing users the next time they run the report. 

Here's a question – do we need two? What if we just created one `use` named `prepare` that runs all four steps identified in @channemann's docs for looping?

**Comment by scottleibrand** [comment]
I like the idea of keeping all four available as individual reports that
you can run for testing, but also creating a single "prepare" use command
that runs all four at once.  I think the idea of two was sort of a
compromise between those two options, but if we can have it both ways
instead, I like that better.

-Scott

**Comment by bewest** [comment]
I really like the `prepare` step idea, now that we know more about what kinds of things need to be done, if all four are basically munging the data for the same reason, it would make a lot of sense to put it into a single use.  On the other hand, renaming the uses/device might help as well?  `openaps use normalize [dedupe,basals,schema,since,all]`.  Or were you thinking single new use, eg `all` with flags that can express which phases to run perhaps? `openaps use normalize all [--with,--without=foo]`?
