### ISSUE TITLE
Openaps reporting support

### ISSUE THREAD

**Issue by loudnate** [loudnate/openaps-mmhistorytools#4]
@bewest you mentioned optional args aren't compatible with report serialization, is that accurate? Should I change all use arguments to `'-'` in this plugin?

**Comment by bewest** [comment]
Optional args are supported.

The problem is when using argparse, we/I expect to serialize the result to a dictionary, which is then serialized into the INI config file.  If one of the value/keys is a "file" object, it can't be serialized into the INI.

The ugly hack around this is to avoid using non-primitive type-helpers in argparse, so that the input and output for get_params is consistent and can be serialized to INI.  After it's been sanitized is when I re-invoke argparser's type-helpers.  Sorry for the awkwardness.
